project:
  type: website
  output-dir: docs

website:
  title: "Ina Krapp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



